### ISSUE TITLE
Using `step` command on a prepared statement which has no more data should not return `true`

### ISSUE THREAD

**Issue by Oldes** [Siskin-framework/Rebol-SQLite#2]
It can be demonstrated using:
```rebol
sqlite: import 'sqlite
with sqlite [
	db: open %temp.db
	;; create a table with just one row
	exec db {
BEGIN TRANSACTION;
CREATE TABLE Cars(Id INTEGER PRIMARY KEY, Name TEXT, Price INTEGER);
INSERT INTO "Cars" VALUES(1,'Audi',52642);
COMMIT;}
	;; prepare the statement
	stmt: prepare db "SELECT * FROM Cars"
	;; get first row...
	probe step stmt ;== [1 "Audi" 52642]
	;; try to get row past end...
	probe step stmt ;== true; but it should be none
	close db
]
try [delete %temp.db]
```

**Comment by fvanzeveren** [comment]
Hello Oldes
I think you introduced a new bug.
It used to work with the following code:
```

rec: sqlite/step stmt
while [not strict-equal? rec true] [
  probe rec: sqlite/step stmt
]
```
But now, the following code stops after the first record, not going through the rest
```
while [not none? rec] [
  probe rec: sqlite/step stmt
]
```
Regards

**Comment by Oldes** [comment]
It is not a bug.. I changed the return value to `none` when there is no result.

**Comment by Oldes** [comment]
I am drunk, but I think you should use:
```rebol
while [rec: sqlite/step stmt] [
  probe rec
]
```

**Comment by fvanzeveren** [comment]
Hello Oldes
Please, could you run the following script which demonstrates the issue with the `sqlite/step` returning `none!` after the first record.
Note also in the insert statement, the necessity of calling `sqlite/reset stmt` after each call to `sqlite/step stmt`, otherwise only the first record is inserted. THis is very painfull :)

[populatedb.txt](https://github.com/Siskin-framework/Rebol-SQLite/files/11714895/populatedb.txt)

Cheers

François

**Comment by fvanzeveren** [comment]
Hi Oldes
I understand my issue, I know have to use the `rows` refinement explicitely to get one record at a time, like this.
```
while [rec: sqlite/step/rows stmt 1] [
	probe rec
]
```
while in previous version, it was not necessary.

Still, the issue of needing `sqlite/reset` after each `sqlite/step/with` is very annoying!
Also, there is an issue with the `none` value: if you compare the insert statement for the `Authors `table with the final result, you will notice that the none value are not properly handled.

**Comment by Oldes** [comment]
I will check it.. also I should note, that the commands still may change as I still don't know, what would be the most useful in real life. Again.. any ideas are welcome.

**Comment by Oldes** [comment]
I see where the problem is.. it looks that I never used `step` command for _inserts_, just for _selects_. Maybe it would be better to have separate commands for these actions.

**Comment by Oldes** [comment]
Btw... why you don't write a wrapper functions? Like:
```rebol
new-book-instance!: sqlite/prepare db {
	INSERT INTO BookInstances (book_id, imprint, due_back, status) VALUES (?,?,?,?)
}
new-book-instance: func[data][
	data: reduce/only/no-set :data
	sqlite/step/with new-book-instance! :data
	sqlite/reset new-book-instance!
	data
]

foreach row [
	[1 "London Gollancz, 2014." false "Available"]
	[2 "Gollancz, 2011." false "Loaned"]
	[3 "Gollancz, 2015." false false]
	[4 "New York Tom Doherty Associates, 2016." false "Available"]
	[4 "New York Tom Doherty Associates, 2016." false "Available"]
	[4 "New York Tom Doherty Associates, 2016." false "Available"]
	[5 "New York, NY Tom Doherty Associates, LLC, 2015." false "Available"]
	[5 "New York, NY Tom Doherty Associates, LLC, 2015." false "Maintenance"]
	[5 "New York, NY Tom Doherty Associates, LLC, 2015." false "Loaned"]
	[1 "Imprint XXX2" false false]
	[2 "Imprint XXX3" false false]
][
	new-book-instance row
]
```
I will probably write the scheme to allow code like:
```rebol
db: open sqlite:books.db
insert db [
	"INSERT INTO BookInstances (book_id, imprint, due_back, status) VALUES (?,?,?,?)"
	[1 "London Gollancz, 2014." false "Available"]
	[2 "Gollancz, 2011." false "Loaned"]
	[3 "Gollancz, 2015." false false]
	[4 "New York Tom Doherty Associates, 2016." false "Available"]
	[4 "New York Tom Doherty Associates, 2016." false "Available"]
	[4 "New York Tom Doherty Associates, 2016." false "Available"]
	[5 "New York, NY Tom Doherty Associates, LLC, 2015." false "Available"]
	[5 "New York, NY Tom Doherty Associates, LLC, 2015." false "Maintenance"]
	[5 "New York, NY Tom Doherty Associates, LLC, 2015." false "Loaned"]
	[1 "Imprint XXX2" false false]
	[2 "Imprint XXX3" false false]
]
close db
```

**Comment by fvanzeveren** [comment]
Hello, if you want to see a work-in-progress "real life" example, have a look to 
http://kis.ovh/local-library/

My workaround for the `sqlite/reset` statement is to add this statement to the `sql-run` command defined in my wrapper script.
Same for the `/rows` refinement.
See the file here: 
The wrapper script:
[sqlite.txt](https://github.com/Siskin-framework/Rebol-SQLite/files/11715725/sqlite.txt)
An example of usage
[populatedb.txt](https://github.com/Siskin-framework/Rebol-SQLite/files/11715731/populatedb.txt)

**Comment by Oldes** [comment]
It looks that I should remove the refinements of the `step` command and make the `rows` and `parameters` always required. That would simplify your code.

**Comment by Oldes** [comment]
And I am also not sure if it was good idea to allow getting all rows using single `step` call, because the results may be huge in real life:/ It should be probably handled on the higher level and not in the C side.

**Comment by fvanzeveren** [comment]
> It looks that I should remove the refinements of the `step` command and make the `rows` and `parameters` always required. That would simplify your code.

I am not sure about that: `rows` should default to 1. And `parameters` should remain optional.

> And I am also not sure if it was good idea to allow getting all rows using single `step` call, because the results may be huge in real life:/ It should be probably handled on the higher level and not in the C side.

Agree, by default `step` should return one row at a time, as it was before and as I force in my wrapper code.

Also, I like to have the `sql-run` command to execute 'INSERT', 'UPDATE' and 'DELETE' stmts and `sql-next` to parse the result of a 'SELECT'. 

`while [rec: sql-next stmt] [probe rec]`

**Comment by Oldes** [comment]
I have modified it a little bit so it should work like you wanted, but I will probably rewrite the commands anyway in a future.

**Comment by fvanzeveren** [comment]
> Also, there is an issue with the `none` value: if you compare the insert statement for the `Authors `table with the final result, you will notice that the none value are not properly handled.

Hello Oldes, 
Just a reminder of this bug. It seems that when setting `none` for one parameter when this parameter was not `none `in the previous invocation of `sqlite/step`, the value of the last invocation is populated.


> Btw... why you don't write a wrapper functions? Like:
> 
> ```rebol
> new-book-instance!: sqlite/prepare db {
> 	INSERT INTO BookInstances (book_id, imprint, due_back, status) VALUES (?,?,?,?)
> }
> new-book-instance: func[data][
> 	data: reduce/only/no-set :data
> 	sqlite/step/with new-book-instance! :data
> 	sqlite/reset new-book-instance!
> 	data
> ]
> 
> foreach row [
> 	[1 "London Gollancz, 2014." false "Available"]
> 	[2 "Gollancz, 2011." false "Loaned"]
> 	[3 "Gollancz, 2015." false false]
> 	[4 "New York Tom Doherty Associates, 2016." false "Available"]
> 	[4 "New York Tom Doherty Associates, 2016." false "Available"]
> 	[4 "New York Tom Doherty Associates, 2016." false "Available"]
> 	[5 "New York, NY Tom Doherty Associates, LLC, 2015." false "Available"]
> 	[5 "New York, NY Tom Doherty Associates, LLC, 2015." false "Maintenance"]
> 	[5 "New York, NY Tom Doherty Associates, LLC, 2015." false "Loaned"]
> 	[1 "Imprint XXX2" false false]
> 	[2 "Imprint XXX3" false false]
> ][
> 	new-book-instance row
> ]
> ```
> 
> I will probably write the scheme to allow code like:
> 
> ```rebol
> db: open sqlite:books.db
> insert db [
> 	"INSERT INTO BookInstances (book_id, imprint, due_back, status) VALUES (?,?,?,?)"
> 	[1 "London Gollancz, 2014." false "Available"]
> 	[2 "Gollancz, 2011." false "Loaned"]
> 	[3 "Gollancz, 2015." false false]
> 	[4 "New York Tom Doherty Associates, 2016." false "Available"]
> 	[4 "New York Tom Doherty Associates, 2016." false "Available"]
> 	[4 "New York Tom Doherty Associates, 2016." false "Available"]
> 	[5 "New York, NY Tom Doherty Associates, LLC, 2015." false "Available"]
> 	[5 "New York, NY Tom Doherty Associates, LLC, 2015." false "Maintenance"]
> 	[5 "New York, NY Tom Doherty Associates, LLC, 2015." false "Loaned"]
> 	[1 "Imprint XXX2" false false]
> 	[2 "Imprint XXX3" false false]
> ]
> close db
> ```

Nice suggestion. I will investigate this indeed. Looks very elegant. I like it!

**Comment by Oldes** [comment]
Can you give me some short example of the `none` issue? And maybe create a new issue for it?

**Comment by Oldes** [comment]
Ok.. I can see the issue. Will fix it.
