### ISSUE TITLE
[WISH] There should be a possibility to get column names from a statement

### ISSUE THREAD

**Issue by Oldes** [Siskin-framework/Rebol-SQLite#4]
Something like:
```rebol
stmt: sqlite/prepare db "SELECT family_name, date_of_birth FROM Authors"
sqlite/columns stmt ;== [ "family_name" "date_of_birth"]
```
Or maybe using words, if possible `[family_name date_of_birth]`.

**Comment by fvanzeveren** [comment]
@Oldes 

somehow, it would be nice to be able to access the result with name attributes:
```
stmt: sqlite/prepare db "SELECT family_name, date_of_birth FROM Authors"
rec: sqlite/step stmt
print rec/family-name
print rec/date-of-birth
```
:)

**Comment by Oldes** [comment]
But that would make sense only if it would be one row result... would it be ok? Also you should submit a new issue for new requests.

**Comment by Oldes** [comment]
And how you would solve the problem, that in SQLite, the column names may not be directly convertible to Rebol words?
Like in case:
```rebol
stmt: prepare db "select randomblob(16)"
rec: sqlite/step stmt
```
It is not possible to have a word `randomblob(16)` in Rebol.
